import React, { useRef, useState } from 'react';
import { View, Pressable, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as ImagePicker from 'expo-image-picker';
import { useIsFocused } from '@react-navigation/native';
import { Props } from './navigation';
import { C, Icon, PlantImage, Txt, s } from './ui';
export function Camera({navigation}:Props<'Camera'>){
 const camera=useRef<CameraView>(null); const [permission,requestPermission]=useCameraPermissions(); const [enabled,setEnabled]=useState(false); const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [torch,setTorch]=useState(false);const [facing,setFacing]=useState<'back'|'front'>('back');const [error,setError]=useState('');const focused=useIsFocused();
 const capture=async()=>{if(busy)return;setError('');setBusy(true);try{if(!enabled){const result=permission?.granted?permission:await requestPermission();if(result.granted){setEnabled(true);}else setError('Camera access is off. Choose a gallery photo or use the example.');return;}if(!ready||!camera.current)return;const result=await camera.current.takePictureAsync({quality:.8});if(result)navigation.replace('Result',{kind:'peace-lily',photo:result.uri});}catch{setError('Camera unavailable. Try the gallery or use the example.');}finally{setBusy(false);}};
 const gallery=async()=>{if(busy)return;setBusy(true);setError('');try{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.8});if(!result.canceled)navigation.replace('Result',{kind:'peace-lily',photo:result.assets[0].uri});}catch{setError('Could not open the gallery. Please try again.');}finally{setBusy(false);}};
 return <View style={{flex:1,backgroundColor:'#E3E4D5'}}>{enabled&&permission?.granted&&focused?<CameraView ref={camera} style={StyleSheet.absoluteFill} facing={facing} enableTorch={torch} onCameraReady={()=>setReady(true)} onMountError={()=>{setEnabled(false);setReady(false);setError('No camera available. Use a photo from your gallery.');}}/>:<View style={[StyleSheet.absoluteFill,{alignItems:'center',justifyContent:'center'}]}><PlantImage kind="peace-lily" size={315}/></View>}
 <SafeAreaView style={{flex:1}}><View style={{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:14}}><Pressable accessibilityRole="button" accessibilityLabel="Close camera" onPress={navigation.goBack} style={cs.icon}><Icon name="close" color={enabled?'white':C.ink}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={torch?'Turn flash off':'Turn flash on'} disabled={!enabled} onPress={()=>setTorch(!torch)} style={cs.icon}><Icon name={torch?'flash':'flash-outline'} color={enabled?'white':C.ink}/></Pressable></View>
 <View style={{alignItems:'center',padding:16}}><Txt style={[s.bold,{fontSize:21,color:enabled?'white':C.ink}]}>Center your plant</Txt><Txt small style={{textAlign:'center',color:enabled?'white':C.ink}}>Make sure the plant is in focus{ '\n' }and well lit.</Txt></View>
 <View pointerEvents="none" style={{flex:1,alignItems:'center',justifyContent:'center'}}><View style={{width:280,height:300}}>{(['tl','tr','bl','br'] as const).map(corner=><View key={corner} style={{position:'absolute',width:24,height:24,borderColor:'white',borderTopWidth:corner[0]==='t'?3:0,borderBottomWidth:corner[0]==='b'?3:0,borderLeftWidth:corner[1]==='l'?3:0,borderRightWidth:corner[1]==='r'?3:0,top:corner[0]==='t'?0:undefined,bottom:corner[0]==='b'?0:undefined,left:corner[1]==='l'?0:undefined,right:corner[1]==='r'?0:undefined,borderRadius:4}}/>)}</View></View>
 <View style={{backgroundColor:enabled?'#23271ED9':'#444A36',padding:20,gap:10}}>{!!error&&<Txt small style={{color:'#FFDDCF',textAlign:'center'}}>{error}</Txt>}<View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-around'}}><Pressable accessibilityRole="button" accessibilityLabel="Choose from gallery" onPress={gallery} disabled={busy} style={cs.icon}><Icon name="images-outline" color="white" size={26}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={enabled?'Take photo':'Enable camera'} disabled={busy||(enabled&&!ready)} onPress={capture} style={({pressed})=>({width:72,height:72,borderRadius:36,borderWidth:3,borderColor:'white',padding:5,opacity:busy?.5:pressed?.7:1})}><View style={{flex:1,borderRadius:32,backgroundColor:'white'}}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Switch camera" disabled={!enabled} onPress={()=>{setReady(false);setFacing(facing==='back'?'front':'back');}} style={cs.icon}><Icon name="camera-reverse-outline" color="white" size={27}/></Pressable></View><Txt small style={{textAlign:'center',color:'#A2C76D',fontFamily:'NunitoSans_700Bold'}}>PHOTO</Txt>{!enabled&&<Pressable accessibilityRole="button" onPress={()=>navigation.replace('Result',{kind:'peace-lily'})} style={{padding:8}}><Txt small style={{textAlign:'center',color:'white'}}>Use example photo</Txt></Pressable>}</View></SafeAreaView></View>;
}
const cs=StyleSheet.create({icon:{width:48,height:48,alignItems:'center',justifyContent:'center'}});
