import React, { useRef, useState } from 'react';
import { View, Pressable, ScrollView, Switch } from 'react-native';
import { createBottomTabNavigator, BottomTabScreenProps } from '@react-navigation/bottom-tabs';
import { useScrollToTop } from '@react-navigation/native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Props } from './navigation';
import { useStore } from './store';
import { CareEvent, Plant, guidanceFor, plantStatus } from './model';
import { Badge, Button, Card, C, Chips, Enter, Field, Icon, IconButton, Logo, Notice, Page, PlantImage, Row, Title, Txt, s } from './ui';
import { SuccessMark } from './motion';
import { Choices, SectionTabs } from './conversation';

type GardenTabs={Home:undefined;Plants:undefined;Activity:undefined;Profile:undefined};
const Tabs=createBottomTabNavigator<GardenTabs>();
export function Main({navigation,route}:Props<'Main'>){const insets=useSafeAreaInsets();return <Tabs.Navigator initialRouteName={route.params?.tab??'Home'} screenOptions={({route:r})=>({headerShown:false,animation:'none',tabBarActiveTintColor:'#54882B',tabBarInactiveTintColor:C.muted,tabBarStyle:{backgroundColor:'#FAFBF8',borderTopColor:C.border,paddingTop:6,paddingBottom:Math.max(insets.bottom,8),height:64+insets.bottom},tabBarLabelStyle:{fontFamily:'NunitoSans_400Regular',fontSize:11},tabBarIcon:({focused,color})=><Icon color={color} size={22} name={r.name==='Home'?focused?'home':'home-outline':r.name==='Plants'?'leaf-outline':r.name==='Activity'?'time-outline':'person-circle-outline'}/>})}>{(['Home','Plants','Activity','Profile'] as const).map(name=><Tabs.Screen key={name} name={name}>{props=><GardenTab {...props} rootNavigation={navigation}/>}</Tabs.Screen>)}</Tabs.Navigator>;}

const soilLabel:Record<string,string>={dry:'Dry',slightly_moist:'Slightly moist',moist:'Moist',wet:'Very wet',not_sure:'Not sure'};
const visualLabel:Record<string,string>={great:'Looks great',different:'A little different',unwell:'Not doing well',not_sure:'Not sure'};
const known=(value?:string)=>value&& !['Not sure',"I don't know"].includes(value);
function PlantRow({plant,onPress}:{plant:Plant;onPress:()=>void}) {
 const {data}=useStore();const g=guidanceFor(data,plant.id);
 return <Pressable accessibilityRole="button" accessibilityLabel={`Open ${plant.name}`} onPress={onPress} style={({pressed})=>({flexDirection:'row',alignItems:'center',gap:16,paddingVertical:12,borderBottomWidth:1,borderColor:C.border,backgroundColor:pressed?C.pale:'transparent'})}>
 <PlantImage kind={plant.kind} uri={plant.photo} size={76}/><View style={{flex:1,gap:4}}><Txt style={s.bold}>{plant.name}</Txt><Txt small>{known(plant.room)?plant.room:plant.species}</Txt><Txt small style={{color:C.ink}}>{g.soil?`Soil · ${soilLabel[g.soil]}`:g.action==='Check soil'?'Ready for a check-in':g.title}</Txt></View><Icon name="chevron-forward" size={18}/></Pressable>;
}
function GardenTab({route,navigation:tabs,rootNavigation:navigation}:BottomTabScreenProps<GardenTabs>&{rootNavigation:Props<'Main'>['navigation']}) {
 const {data}=useStore();const tab=route.name;const ref=useRef<ScrollView>(null);useScrollToTop(ref);
 const [filter,setFilter]=useState('All plants');const rooms=Array.from(new Set(data.plants.map(p=>p.room).filter(known)));
 const plants=data.plants.filter(p=>filter==='All plants'||p.room===filter);const waiting=data.plants.filter(p=>guidanceFor(data,p.id).action==='Check soil');
 const attention=waiting[0]??data.plants[0];const guide=attention?guidanceFor(data,attention.id):null;const open=(p:Plant)=>navigation.navigate('Details',{id:p.id});
 return <Page tabScreen scrollRef={ref} header={tab==='Home'?<Logo/>:<Title>{tab}</Title>} right={tab!=='Activity'?<IconButton name={tab==='Profile'?'settings-outline':'add'} label={tab==='Profile'?'Settings':'Add plant'} onPress={()=>navigation.navigate(tab==='Profile'?'Settings':'AddPlant')}/>:undefined}>
 {tab==='Home'&&<><View style={{gap:6,paddingVertical:8}}><Title>{new Date().getHours()<12?'Good morning':new Date().getHours()<18?'Good afternoon':'Good evening'}, {data.name.split(' ')[0]}.</Title><Txt style={{color:C.muted}}>{waiting.length?`${waiting.length} ${waiting.length===1?'plant is':'plants are'} ready for a check-in.`:data.plants.length?'Your latest care, at a glance.':'Let’s get to know your first plant.'}</Txt></View>
 {attention&&guide?<><Card><Pressable accessibilityRole="button" accessibilityLabel={`View ${attention.name} details`} onPress={()=>open(attention)} style={[s.split,{justifyContent:'flex-start'}]}><PlantImage kind={attention.kind} uri={attention.photo} size={88}/><View style={{flex:1,gap:5}}><Txt style={[s.bold,{fontSize:19,lineHeight:24}]}>{attention.name}</Txt><Txt small>{guide.title}</Txt></View><Icon name="chevron-forward" size={18}/></Pressable><Txt small style={{color:C.ink}}>{guide.reason}</Txt><Button title={guide.action} onPress={()=>guide.action==='Check soil'?navigation.navigate('LogCare',{id:attention.id,mode:'soil'}):open(attention)}/></Card>
 <View style={[s.split,{marginTop:8}]}><Txt style={s.bold}>Your plants</Txt><Pressable accessibilityRole="button" onPress={()=>tabs.navigate('Plants')} style={{minHeight:44,justifyContent:'center'}}><Txt style={s.link}>See all</Txt></Pressable></View><View>{data.plants.slice(0,3).map(p=><PlantRow key={p.id} plant={p} onPress={()=>open(p)}/>)}</View>
 {data.events.length>0&&<><View style={[s.split,{marginTop:8}]}><Txt style={s.bold}>Recently recorded</Txt><Pressable accessibilityRole="button" onPress={()=>tabs.navigate('Activity')} style={{minHeight:44,justifyContent:'center'}}><Txt style={s.link}>History</Txt></Pressable></View>{data.events.slice(-2).reverse().map(e=><TimelineEvent key={e.id} event={e} name={data.plants.find(p=>p.id===e.plantId)?.name}/>)}</>}</>:<EmptyGarden onAdd={()=>navigation.navigate('AddPlant')}/>}</>}
 {tab==='Plants'&&<>{rooms.length>1&&<Chips values={['All plants',...rooms]} value={filter} onChange={setFilter}/>}<View>{plants.map(p=><PlantRow key={p.id} plant={p} onPress={()=>open(p)}/>)}</View>{!data.plants.length&&<EmptyGarden onAdd={()=>navigation.navigate('AddPlant')}/>}</>}
 {tab==='Activity'&&<ActivityContent open={id=>navigation.navigate('Details',{id})}/>}
 {tab==='Profile'&&<><View style={[s.split,{justifyContent:'flex-start',paddingVertical:12}]}><View style={{padding:16,borderRadius:40,backgroundColor:C.pale}}><Icon name="person-outline" size={28}/></View><View style={{flex:1}}><Title>{data.name}</Title><Txt small>{data.plants.length} {data.plants.length===1?'plant':'plants'} · {data.events.length} care records</Txt></View></View>
 <Txt small>GARDENING PROFILE</Txt><View><Row icon="leaf-outline" title="Experience" value={data.caregiver?.experience??'Not set'} onPress={()=>navigation.navigate('Onboarding',{replay:true})}/><Row icon="chatbubble-outline" title="Guidance" value={data.caregiver?.detail??'Guided'} onPress={()=>navigation.navigate('Settings')}/><Row icon="flower-outline" title="Your plants" onPress={()=>tabs.navigate('Plants')}/></View>
 <Txt small style={{marginTop:16}}>PREFERENCES</Txt><View><Row icon="notifications-outline" title="Notifications" onPress={()=>navigation.navigate('Settings')}/><Row icon="bag-outline" title="My subscription" value={data.plan} onPress={()=>navigation.navigate('Plans')}/><Row icon="help-circle-outline" title="How Rootera learns" onPress={()=>navigation.navigate('Article',{title:'Learning with you',content:'Rootera uses your observations, watering history and the environment you describe. Suggestions explain their source. A pattern needs observations across several watering cycles, rather than a fixed number of days. Weather and automatic photo analysis are not connected yet. Photos remain local to this device.'})}/></View></>}
 </Page>;
}
function EmptyGarden({onAdd}:{onAdd:()=>void}) {return <View style={{gap:20,paddingVertical:24,alignItems:'center'}}><PlantImage size={180}/><Title center>Your garden starts here</Title><Txt style={s.sub}>Add a plant and make your first observation.</Txt><View style={{alignSelf:'stretch'}}><Button title="Add a plant" icon="add" onPress={onAdd}/></View></View>;}
function ActivityContent({open}:{open:(id:string)=>void}) {
 const {data}=useStore();const [category,setCategory]=useState('All');const attention=data.plants.filter(p=>guidanceFor(data,p.id).action==='Check soil');const events=[...data.events].reverse();
 const empty=category==='To check'?!attention.length:category==='Learning'?!data.plants.length:!events.length;
 return <><SectionTabs values={['All','To check','Learning','History']} value={category} onChange={setCategory}/>
 {category==='To check'&&attention.map(p=><Pressable accessibilityRole="button" key={p.id} onPress={()=>open(p.id)} style={{paddingVertical:16,borderBottomWidth:1,borderColor:C.border,gap:6}}><View style={s.split}><Txt style={s.bold}>{p.name}</Txt><Icon name="chevron-forward" size={18}/></View><Txt small>{guidanceFor(data,p.id).reason}</Txt></Pressable>)}
 {category==='Learning'&&data.plants.map(p=>{const g=guidanceFor(data,p.id);return <Pressable accessibilityRole="button" key={p.id} onPress={()=>open(p.id)} style={{paddingVertical:16,borderBottomWidth:1,borderColor:C.border,gap:6}}><View style={s.split}><Txt style={s.bold}>{p.name}</Txt><Icon name="chevron-forward" size={18}/></View><Txt small>{g.baseline_days===null?'More watering cycles are needed to find a pattern.':`First dry check: typically ${g.baseline_days} days after watering, across ${g.completed_cycles} cycles.`}</Txt></Pressable>;})}
 {(category==='All'||category==='History')&&events.map(e=><Pressable accessibilityRole="button" key={e.id} onPress={()=>open(e.plantId)}><TimelineEvent event={e} name={data.plants.find(p=>p.id===e.plantId)?.name}/></Pressable>)}
 {empty&&<View style={{paddingVertical:32,gap:10}}><Icon name="time-outline" size={28}/><Txt style={s.bold}>{category==='To check'?'No checks waiting':'No records yet'}</Txt><Txt small>{category==='To check'?'Open a plant whenever you notice something new.':'Your watering and observations will appear here.'}</Txt></View>}</>;
}
function TimelineEvent({event,name}:{event:CareEvent;name?:string}) {
 const date=new Date(event.at);const today=date.toDateString()===new Date().toDateString();
 return <View style={{paddingVertical:14,gap:5,borderBottomWidth:1,borderColor:C.border}}><View style={s.split}><View style={{flex:1}}><Txt style={s.bold}>{name?`${name} · `:''}{event.type}</Txt></View><Icon name={event.type==='Watered'?'water-outline':'chatbubble-outline'} size={18}/></View><Txt small>{today?'Today':date.toLocaleDateString(undefined,{month:'short',day:'numeric'})} · {date.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})} · Recorded by you</Txt>{!!event.soil&&<Txt>{soilLabel[event.soil]}</Txt>}{!!event.visual&&<Txt>{visualLabel[event.visual]}</Txt>}{event.amount_ml!=null&&<Txt>{event.amount_ml} ml</Txt>}{!!event.note&&<Txt>{event.note}</Txt>}</View>;
}
export function Details({navigation,route}:Props<'Details'>) {
 const {data,update}=useStore();const plant=data.plants.find(p=>p.id===route.params.id);const [tab,setTab]=useState('Overview');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [watered,setWatered]=useState(false);const lock=useRef(false);const pending=useRef<{id:string;at:string}|null>(null);
 const recordWater=async()=>{if(lock.current||watered)return;lock.current=true;setBusy(true);setError('');pending.current??={id:`water-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,at:new Date().toISOString()};const event=pending.current;try{await update(d=>({...d,events:[...d.events.filter(e=>e.id!==event.id),{...event,plantId:route.params.id,type:'Watered',source:'USER',note:''}]}));setWatered(true);navigation.setParams({feedback:'Watering recorded'});}catch(e){setError(e instanceof Error?e.message:'Could not save watering.');}finally{lock.current=false;setBusy(false);}};
 if(!plant)return <Page back={navigation.goBack}><Title>Plant not found</Title></Page>;
 const guide=guidanceFor(data,plant.id);const events=data.events.filter(e=>e.plantId===plant.id).slice().reverse();
 return <Page hideStorageError={!!error} back={()=>{if(!busy)navigation.goBack();}}>
 {!!route.params.feedback&&<Enter key={route.params.feedback}><View accessibilityLiveRegion="polite" style={[s.split,{paddingLeft:12,backgroundColor:C.pale,borderRadius:12}]}><View style={{flexDirection:'row',alignItems:'center',gap:8,flex:1}}><Icon name="checkmark-circle" size={20}/><Txt small style={{color:C.ink}}>{route.params.feedback}</Txt></View><IconButton name="close" label="Dismiss confirmation" onPress={()=>navigation.setParams({feedback:undefined})}/></View></Enter>}
 <View style={[s.split,{paddingVertical:8}]}><PlantImage kind={plant.kind} uri={plant.photo} size={116}/><View style={{flex:1,gap:6}}><Title>{plant.name}</Title><Txt small style={{fontStyle:'italic'}}>{plant.species}</Txt><Txt small>{known(plant.room)?plant.room:'Location not set'}</Txt></View></View>
 <SectionTabs values={['Overview','Learning','History']} value={tab} onChange={setTab}/>
 {tab==='Overview'&&<View style={{gap:20}}><View style={{gap:8}}><Txt style={[s.bold,{fontSize:20,lineHeight:25}]}>{guide.title}</Txt><Txt small style={{color:C.ink}}>{guide.reason}</Txt></View>
 <View style={{gap:10}}><Button secondary={guide.action!=='Check soil'} title="Check soil" onPress={()=>navigation.navigate('LogCare',{id:plant.id,mode:'soil'})} disabled={busy}/><View style={{flexDirection:'row',gap:8}}><View style={{flex:1}}><Button secondary={guide.soil!=='dry'} title={busy?'Saving…':watered?'Watering recorded':'I watered this plant'} icon={watered?'checkmark':undefined} disabled={busy||watered} onPress={()=>void recordWater()}/></View><IconButton name="ellipsis-horizontal" label="Record watering with details" onPress={()=>{if(!busy)navigation.navigate('LogCare',{id:plant.id,mode:'water'});}}/></View><Pressable accessibilityRole="button" onPress={()=>navigation.navigate('LogCare',{id:plant.id,mode:'visual'})} style={{minHeight:44,justifyContent:'center',alignItems:'center'}}><Txt style={s.link}>Record how it looks</Txt></Pressable></View>
 {!!error&&<Txt style={{color:C.orange}}>{error}</Txt>}
 <View><Txt small>LATEST CHECKS · REPORTED BY YOU</Txt><Row icon="water-outline" title="Soil" value={guide.soil?soilLabel[guide.soil]:'No current check'}/><Row icon="leaf-outline" title="Appearance" value={guide.visual?visualLabel[guide.visual]:'No current check'}/></View>
 <View><Txt small>ENVIRONMENT · PROVIDED BY YOU</Txt><Row icon="sunny-outline" title="Light" value={known(plant.light)?plant.light:'Not set'}/><Row icon="flower-outline" title="Pot" value={known(plant.pot)?plant.pot:'Not set'}/>{known(plant.drainage)&&<Row icon="water-outline" title="Drainage hole" value={plant.drainage}/>}{known(plant.substrate)&&<Txt small style={{paddingTop:12}}>{plant.substrate}</Txt>}</View></View>}
 {tab==='Learning'&&<View style={{gap:16}}><Txt style={[s.bold,{fontSize:20,lineHeight:25}]}>Learning from your observations</Txt><Txt small>{guide.baseline_days===null?'There isn’t enough history to describe a watering pattern yet. Keep recording what you notice.':`Across ${guide.completed_cycles} cycles, your first dry check came about ${guide.baseline_days} days after watering.`}</Txt><Txt style={s.bold}>What contributes</Txt>{guide.signals.map(signal=><View key={signal} style={{flexDirection:'row',gap:10}}><Icon name="checkmark" size={18}/><Txt>{signal}</Txt></View>)}<Txt small style={{borderTopWidth:1,borderColor:C.border,paddingTop:16}}>A dry check depends on when you observe the soil. It is not a measured drying time or a watering schedule.</Txt></View>}
 {tab==='History'&&(events.length?events.map(e=><TimelineEvent key={e.id} event={e}/>):<Txt small>No care records yet. Make a check-in from Overview.</Txt>)}
 </Page>;
}
export function LogCare({navigation,route}:Props<'LogCare'>) {
 const {data,update}=useStore();const plant=data.plants.find(p=>p.id===route.params.id);const mode=route.params.mode??'soil';const [choice,setChoice]=useState('');const [note,setNote]=useState('');const [amount,setAmount]=useState('');const [details,setDetails]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const lock=useRef(false);const eventId=useRef(`care-${Date.now()}-${Math.random().toString(36).slice(2,8)}`);const at=useRef(new Date().toISOString());
 const save=async()=>{if(lock.current||(mode!=='water'&&!choice))return;if(amount&&(!Number.isFinite(Number(amount))||Number(amount)<0||Number(amount)>100000)){setError('Enter a valid amount from 0 to 100000 ml.');return;}lock.current=true;setBusy(true);setError('');try{const soil=Object.keys(soilLabel).find(k=>soilLabel[k]===choice) as CareEvent['soil'];const visual=Object.keys(visualLabel).find(k=>visualLabel[k]===choice) as CareEvent['visual'];await update(d=>({...d,events:[...d.events.filter(e=>e.id!==eventId.current),{id:eventId.current,plantId:route.params.id,at:at.current,source:'USER',type:mode==='water'?'Watered':mode==='soil'?'Soil check':'Observation',soil:mode==='soil'?soil:null,visual:mode==='visual'?visual:null,amount_ml:mode==='water'&&amount?Number(amount):null,note:note.trim()}]}));navigation.popTo('Details',{id:route.params.id,feedback:mode==='water'?'Watering recorded':mode==='soil'?'Soil check saved':'Appearance check saved'});}catch(e){setError(e instanceof Error?e.message:'Could not save. Please try again.');}finally{lock.current=false;setBusy(false);}};
 if(!plant)return <Page back={navigation.goBack}><Title>Plant not found</Title></Page>;
 return <Page hideStorageError={!!error} back={()=>{if(!busy)navigation.goBack();}} footer={<Button title={busy?'Saving…':mode==='water'?'Record watering':'Save check-in'} disabled={busy||(mode!=='water'&&!choice)} onPress={()=>void save()}/>}>
 <View style={{flexDirection:'row',alignItems:'center',gap:10}}><PlantImage kind={plant.kind} uri={plant.photo} size={48}/><Txt small>{plant.name}</Txt></View><Title>{mode==='soil'?'How does the soil feel?':mode==='visual'?'How does it look?':'Record watering'}</Title><Txt style={{color:C.muted}}>{mode==='water'?'Save watering for now. Details are optional.':mode==='soil'?'Check gently below the surface, then choose what you feel.':'Record what you notice in the leaves and stems.'}</Txt>
 {mode!=='water'&&<Choices options={Object.values(mode==='soil'?soilLabel:visualLabel)} value={choice} onChange={v=>{setChoice(v);setError('');}}/>}
 {mode==='visual'&&['A little different','Not doing well'].includes(choice)&&<Enter><Field label="What changed? (optional)" value={note} onChangeText={setNote} placeholder="For example, one leaf is yellow"/></Enter>}
 {mode==='water'&&<><Pressable accessibilityRole="button" accessibilityState={{expanded:details}} onPress={()=>setDetails(!details)} style={{minHeight:48,justifyContent:'center'}}><Txt style={s.link}>{details?'Hide details':'Add details (optional)'}</Txt></Pressable>{details&&<Enter><View style={{gap:16}}><Field label="Amount (ml)" value={amount} onChangeText={setAmount} numeric/><Field label="Notes" value={note} onChangeText={setNote}/></View></Enter>}</>}
 {!!error&&<Txt style={{color:C.orange}}>{error}</Txt>}</Page>;
}
export function Notifications({navigation}:Props<'Notifications'>){return <Page back={navigation.goBack}><Title>Activity</Title><ActivityContent open={id=>navigation.navigate('Details',{id})}/></Page>;}
export function Settings({navigation}:Props<'Settings'>){const {data,update}=useStore();const [name,setName]=useState(data.name);const [reminders,setReminders]=useState(data.reminders);const [detail,setDetail]=useState<'Guided'|'Concise'>(data.caregiver?.detail??'Guided');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const save=async()=>{if(busy||!name.trim())return;setBusy(true);try{await update(d=>({...d,name:name.trim(),reminders,caregiver:{experience:d.caregiver?.experience??'Just starting',plant_count:d.caregiver?.plant_count??'1–3',detail}}));navigation.goBack();}catch(e){setError(e instanceof Error?e.message:'Could not save settings.');}finally{setBusy(false);}};return <Page back={navigation.goBack} footer={<Button title={busy?'Saving…':'Save changes'} disabled={busy||!name.trim()} onPress={save}/>}><Title>Make Rootera yours</Title><Field label="Your name" value={name} onChangeText={setName}/><Txt style={s.bold}>How much detail feels right?</Txt><Choices options={['Guided','Concise']} value={detail} onChange={v=>setDetail(v as 'Guided'|'Concise')}/><Card><View style={s.split}><View style={{flex:1}}><Txt style={s.bold}>Care reminders</Txt><Txt small>Saved with your profile</Txt></View><Switch accessibilityLabel="Care reminders" value={reminders} onValueChange={setReminders} disabled={busy} trackColor={{true:C.green}}/></View></Card><Txt small>Push delivery is not connected yet. Your in-app activity remains available.</Txt><Button title="Edit gardening profile" secondary disabled={busy} onPress={()=>navigation.navigate('Onboarding',{replay:true})}/>{!!error&&<Txt style={{color:C.orange}}>{error}</Txt>}</Page>;}
export function Article({navigation,route}:Props<'Article'>){return <Page back={navigation.goBack}><Title>{route.params.title}</Title><Txt style={{lineHeight:27}}>{route.params.content}</Txt></Page>;}
