import { CommonActions } from '@react-navigation/native';
import React, { useState } from 'react';
import { View, Pressable } from 'react-native';
import { Props } from './navigation';
import { useStore } from './store';
import { SuccessMark } from './motion';
import { Plan, plans } from './model';
import { Badge, Button, Card, C, Chips, Enter, Icon, Notice, Page, PlantImage, Title, Txt, s } from './ui';
export function Plans({ navigation }: Props<'Plans'>) { const { data } = useStore(); const [selected, select] = useState<Exclude<Plan, 'Free'>>('Grow'); const [billing, setBilling] = useState('Monthly'); return <Page back={navigation.goBack} footer={<><Button title={`Preview ${selected}`} icon="arrow-forward" onPress={() => navigation.navigate('Checkout', { plan: selected, annual: billing === 'Yearly' })}/><Txt small style={{ textAlign: 'center' }}>Demo pricing · No real charges</Txt></>}><Title center>Unlock Rootera+</Title><Txt style={s.sub}>Smarter plant care. Healthier plants.{"\n"}A greener, happier you.</Txt><View style={s.center}><Chips values={['Monthly', 'Yearly']} value={billing} onChange={setBilling}/>{billing === 'Yearly' && <Txt small style={{ color: '#52832A', marginTop: 5 }}>Save 20% · billed annually</Txt>}</View>{plans.map((p, i) => <Enter key={p.name} delay={i * 95}><Pressable accessibilityRole="radio" accessibilityState={{ checked: selected === p.name }} onPress={() => select(p.name)}><Card style={{ borderColor: selected === p.name ? '#7CAC54' : C.border, borderWidth: selected === p.name ? 2 : 1, backgroundColor: selected === p.name ? '#F5FAEF' : C.white }}><View style={{ flexDirection: 'row', gap: 12 }}><PlantImage kind={p.kind} size={70}/><View style={{ flex: 1, gap: 6 }}><View style={s.split}><Txt style={s.bold}>{p.name}</Txt>{p.name === 'Grow' && <Badge text="Most popular"/>}</View><Txt style={s.bold}>R$ {(billing === 'Yearly' ? p.price * 12 * .8 : p.price).toFixed(2).replace('.', ',')}<Txt small>/{billing === 'Yearly' ? 'year' : 'mo'}</Txt></Txt>{p.features.map(f => <View key={f} style={{ flexDirection: 'row', gap: 6 }}><Icon name="checkmark" size={14} color="#689C3E"/><Txt small style={{ color: C.ink }}>{f}</Txt></View>)}</View></View></Card></Pressable></Enter>)}<Txt small>Current plan: {data.plan}. Prices are examples until store products are connected.</Txt></Page>; }
export function Checkout({ navigation, route }: Props<'Checkout'>) { const { update } = useStore(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); return <Page back={navigation.goBack} center footer={<><Button title={busy ? 'Applying…' : 'Activate demo plan'} disabled={busy} onPress={async () => { setBusy(true); try { await update(d => ({ ...d, plan: route.params.plan, annual: route.params.annual })); navigation.dispatch(state => { const paywall = state.routes.findIndex(r => r.name === 'Plans'); const base = state.routes.slice(0, paywall < 0 ? 1 : paywall); const returnTo = base.some(r => r.name === 'AddPlant') ? 'AddPlant' as const : 'Main' as const; const routes = [...base, { name: 'Success' as const, params: { plan: route.params.plan, returnTo } }]; return CommonActions.reset({ ...state, routes, index: routes.length - 1 }); }); } catch { setError('Could not activate the demo plan. Please try again.'); } finally { setBusy(false); } }}/><Button title="Cancel" secondary onPress={navigation.goBack}/></>}><View style={s.center}><Icon name="sparkles" size={55} color={C.green}/></View><Title center>Make room to grow</Title><Card><Txt style={s.bold}>Rootera+ {route.params.plan}</Txt><Txt>{route.params.annual ? 'Annual' : 'Monthly'} · demo subscription</Txt></Card><Notice title="No payment will be taken" text="This activates a simulated entitlement. RevenueCat and store checkout still require your product IDs and account configuration."/>{!!error && <Txt style={{ color: C.orange }}>{error}</Txt>}</Page>; }
export function Success({ navigation, route }: Props<'Success'>) { return <Page center footer={<Button title="Continue" icon="arrow-forward" onPress={() => navigation.goBack()}/>}><Enter><View style={{ alignItems: 'center', gap: 16 }}><SuccessMark/><PlantImage kind="peace-lily" size={240}/><Title center>Your garden just{ '\n' }got smarter</Title><Txt>Rootera+ {route.params.plan} is active in demo mode.</Txt></View></Enter><Notice title="More room for your plants" text="Add more plants and explore the full garden experience." icon="leaf-outline"/><Notice title="Your history stays with you" text="Keep recording care and observations." icon="document-text-outline"/></Page>; }
const sixty = 60;
