import { CommonActions } from '@react-navigation/native';
import React, { useState, useRef, useEffect } from 'react';
import { View, Pressable, TextInput, BackHandler } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Choices, StepLabel } from './conversation';
import { Props } from './navigation';
import { useStore } from './store';
import { addPlant, catalog, limits, PlantKind } from './model';
import { Badge, Button, Card, C, Chips, Enter, Field, Icon, Notice, Page, PlantImage, Title, Txt, Row, s } from './ui';
export function AddPlant({ navigation }: Props<'AddPlant'>) {
 const { data } = useStore(); const limited = data.plants.length >= limits[data.plan];
 return <Page back={navigation.goBack} footer={limited ? <><Button title="Compare plans" onPress={() => navigation.navigate('Plans')}/><Button title="Maybe later" secondary onPress={navigation.goBack}/></> : undefined}><Title center>{limited ? "Your garden is growing" : 'Add a plant'}</Title><Txt style={s.sub}>{limited ? 'Your garden is growing. Choose a plan for more plants and smarter insights.' : 'Choose how you’d like to add your plant.'}</Txt>{limited ? <><View style={s.center}><PlantImage kind="monstera" size={210}/></View><Notice title={`${data.plan} · ${limits[data.plan]} plants`} text="Your existing plants and history remain available."/></> : <>{[{ title: 'Add with a photo', text: 'Take a photo and choose a matching species.', icon: 'camera-outline', route: 'Camera' }, { title: 'Search manually', text: 'Browse our plant collection to find your plant.', icon: 'search-outline', route: 'Search' }].map(m => <Pressable accessibilityRole="button" key={m.title} onPress={() => navigation.navigate(m.route as 'Camera' | 'Search')}><Card style={{ paddingVertical: 28 }}><View style={s.split}><View style={{ backgroundColor: C.pale, padding: 20, borderRadius: 42 }}><Icon name={m.icon as any} size={32}/></View><View style={{ flex: 1, gap: 4 }}><Txt style={s.bold}>{m.title}</Txt><Txt small>{m.text}</Txt></View><Icon name="chevron-forward" size={17}/></View></Card></Pressable>)}<Txt small style={s.sub}>A photo, a name, and a little about its home. You can say “not sure” along the way.</Txt></>}</Page>;
}
export { Camera } from './camera';
export function Search({ navigation }: Props<'Search'>) { const [q, setQ] = useState(''); const results = catalog.filter(p => `${p.name} ${p.species}`.toLowerCase().includes(q.toLowerCase())); return <Page back={navigation.goBack}><Title>Find your plant</Title><Field label="Search species" value={q} onChangeText={setQ} placeholder="Try Aloe Vera"/>{results.map(p => <Pressable accessibilityRole="button" key={p.kind} onPress={() => navigation.navigate('Register', { kind: p.kind })}><Card><View style={s.split}><PlantImage kind={p.kind} size={85}/><View style={{ flex: 1 }}><Txt style={s.bold}>{p.name}</Txt><Txt small>{p.species}</Txt></View><Icon name="chevron-forward"/></View></Card></Pressable>)}{!results.length && <Notice title="No plants found" text="Try Aloe Vera, Peace Lily or Monstera. This starter catalog can be expanded."/>}</Page>; }
export function Result({ navigation, route }: Props<'Result'>) { const [kind, setKind] = useState<PlantKind>(route.params.kind); const plant = catalog.find(p => p.kind === kind)!; return <Page back={navigation.goBack} footer={<Button title="Use this plant" onPress={() => navigation.navigate('Register', { kind, photo: route.params.photo })}/>}><View style={[s.center, { backgroundColor: C.pale, borderRadius: 24 }]}><PlantImage kind={kind} uri={route.params.photo} size={280}/></View><View style={s.split}><View style={{ flex: 1 }}><Title>{plant.name}</Title><Txt small style={{ fontStyle: 'italic' }}>{plant.species}</Txt></View><Badge text="Confirm species"/></View><Notice title="You’re in control" text="This is a manual selection, not an AI match or health diagnosis."/><Txt style={s.bold}>Choose the closest match</Txt><View style={{ gap: 8 }}>{catalog.map(p => <Pressable accessibilityRole="button" accessibilityState={{ selected: p.kind === kind }} key={p.kind} onPress={() => setKind(p.kind)}><Card style={{ borderColor: kind === p.kind ? C.green : C.border, padding: 10 }}><View style={s.split}><PlantImage kind={p.kind} size={45}/><Txt style={{ flex: 1 }}>{p.name}</Txt>{kind === p.kind && <Icon name="checkmark-circle" color={C.green}/>}</View></Card></Pressable>)}</View></Page>; }
export function Register({navigation,route}:Props<'Register'>){
 const {update}=useStore();const species=catalog.find(p=>p.kind===route.params.kind)!;const [step,setStep]=useState(0);const [extra,setExtra]=useState(false);const [potDetails,setPotDetails]=useState(false);const [name,setName]=useState('');const [tenure,setTenure]=useState('Not sure');const [stage,setStage]=useState('Not sure');const [location,setLocation]=useState('Not sure');const [light,setLight]=useState('Not sure');const [window,setWindow]=useState('Not sure');const [pot,setPot]=useState('Not sure');const [drainage,setDrainage]=useState('Not sure');const [material,setMaterial]=useState('Not sure');const [selfWatering,setSelfWatering]=useState('Not sure');const [soil,setSoil]=useState("I don't know");const [busy,setBusy]=useState(false);const [error,setError]=useState('');const id=useRef(`plant-${Date.now()}-${Math.random().toString(36).slice(2,7)}`);
 useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(busy)return true;if(step){setStep(v=>v-1);return true;}return false;});return()=>sub.remove();},[step,busy]);
 const save=async()=>{if(busy)return;setBusy(true);setError('');try{await update(d=>addPlant(d,{...species,id:id.current,name:name.trim()||species.name,photo:route.params.photo,room:location,pot,light,time_with_owner:tenure,stage,environment:{location,near_window:window},drainage,material,self_watering:selfWatering,substrate:soil}));navigation.dispatch(state=>{const start=state.routes.findIndex(r=>r.name==='AddPlant');const routes=[...state.routes.slice(0,start<0?1:start),{name:'Details' as const,params:{id:id.current}}];return CommonActions.reset({...state,routes,index:routes.length-1});});}catch(e){setError(e instanceof Error?e.message:'Could not save your plant.');}finally{setBusy(false);}};
 return <Page back={()=>{if(!busy)step?setStep(step-1):navigation.goBack();}} footer={<Button title={busy?'Saving…':step===1?'Add plant':'Continue'} disabled={busy} onPress={()=>step===0?setStep(1):void save()}/>}>
 <StepLabel step={step+1} total={2} label="Add a plant"/>
 <Enter key={step}><View style={{gap:20,paddingTop:8}}>
 {step===0?<><View style={s.split}><PlantImage kind={species.kind} uri={route.params.photo} size={112}/><View style={{flex:1,gap:4}}><Title>{species.name}</Title><Txt small style={{fontStyle:'italic'}}>{species.species}</Txt></View></View>
 <Field label="Name (optional)" value={name} onChangeText={setName} placeholder={species.name}/>
 <Txt small>You can keep the species name.</Txt>
 <Pressable accessibilityRole="button" accessibilityLabel="More about this plant" accessibilityState={{expanded:extra}} onPress={()=>setExtra(!extra)} style={{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderTopWidth:1,borderColor:C.border}}><Txt style={s.bold}>More about this plant</Txt><Icon name={extra?'chevron-up':'chevron-down'} size={18}/></Pressable>
 {extra&&<Enter><View style={{gap:16}}><Txt small>Optional details to help put future observations in context.</Txt><Txt style={s.bold}>How long have you had it?</Txt><Chips values={['Less than a month','1–6 months','6–12 months','1–3 years','3+ years','Not sure']} value={tenure} onChange={setTenure}/><Txt style={s.bold}>Growth stage</Txt><Chips values={['Seedling','Young','Mature','Not sure']} value={stage} onChange={setStage}/></View></Enter>}</>:
 <><Title>Where will it grow?</Title><Txt style={{color:C.muted}}>Start with what you know. These details help explain how the soil changes.</Txt>
 <Txt style={s.bold}>Location</Txt><Chips values={['Indoors','Outdoors','Balcony / patio','Not sure']} value={location} onChange={setLocation}/>
 <Txt style={s.bold}>Usual light</Txt><Chips values={['Low','Indirect','Bright indirect','Direct sun','Not sure']} value={light} onChange={setLight}/>
 <Pressable accessibilityRole="button" accessibilityLabel="Pot, soil & window" accessibilityState={{expanded:potDetails}} onPress={()=>setPotDetails(!potDetails)} style={{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderTopWidth:1,borderColor:C.border}}><Txt style={s.bold}>Pot, soil & window</Txt><Icon name={potDetails?'chevron-up':'chevron-down'} size={18}/></Pressable>
 {!potDetails&&<Txt small>Optional. You can add the plant without these details.</Txt>}
 {potDetails&&<Enter><View style={{gap:16}}><Txt style={s.bold}>Drainage hole?</Txt><Chips values={['Yes','No','Not sure']} value={drainage} onChange={setDrainage}/><Txt style={s.bold}>Pot size</Txt><Chips values={['Small pot','Medium pot','Large pot','Not sure']} value={pot} onChange={setPot}/><Txt style={s.bold}>Material</Txt><Chips values={['Terracotta','Plastic','Ceramic','Other','Not sure']} value={material} onChange={setMaterial}/><Txt style={s.bold}>Self-watering pot?</Txt><Chips values={['Yes','No','Not sure']} value={selfWatering} onChange={setSelfWatering}/><Txt style={s.bold}>Soil mix</Txt><Choices options={['Regular potting mix','Very draining / chunky','Dense / holds water',"I don't know"]} value={soil} onChange={setSoil}/><Txt style={s.bold}>Near a window?</Txt><Chips values={['Yes','No','Not sure']} value={window} onChange={setWindow}/></View></Enter>}</>}
 {!!error&&<Txt style={{color:C.orange}}>{error}</Txt>}</View></Enter></Page>;
}
