import { CommonActions } from '@react-navigation/native';
import { MoistureProgress } from './motion';
import React, { useState } from 'react';
import { View, Pressable } from 'react-native';
import { Props } from './navigation';
import { useStore } from './store';
import { moisture } from './model';
import { Badge, Button, Card, C, Chips, Enter, Field, Icon, Notice, Page, PlantImage, Row, Title, Txt, s } from './ui';
export function Sensors({ navigation }: Props<'Sensors'>) { const { data } = useStore(); return <Page back={navigation.goBack} footer={<Button title="Add sensor" icon="add" disabled={!data.plants.length} onPress={() => navigation.navigate('Pairing')}/>}><Title center>Sensors & Devices</Title><Txt style={s.sub}>More precision. Deeper insight into your plants.</Txt>{data.sensors.map(d => <Pressable accessibilityRole="button" key={d.id} onPress={() => d.demo ? navigation.navigate('Calibration', { plantId: d.plantId, name: d.name }) : navigation.navigate('Details', { id: d.plantId })}><Card><View style={s.split}><Icon name="hardware-chip-outline" size={36}/><View style={{ flex: 1 }}><Txt style={s.bold}>{d.name}</Txt><Txt small>{data.plants.find(p => p.id === d.plantId)?.name}</Txt></View><Badge text={d.demo ? "Demo device" : "Registered"}/></View><Row icon="water-outline" title="Soil moisture" value={`${d.moisture ?? "—"}% · ${d.demo ? "simulated" : "measured"}`}/><Txt small>Last sample: {(d.observedAt ? new Date(d.observedAt).toLocaleString() : "No reading yet")}</Txt></Card></Pressable>)}{!data.sensors.length && <View style={[s.center, { paddingVertical: 24, gap: 18 }]}><Icon name="hardware-chip-outline" size={66} color={C.green}/><Txt style={s.bold}>No sensors connected yet</Txt></View>}<Notice title="Sensors are optional" text="Your care observations work independently from device measurements."/></Page>; }
export function Pairing({ navigation, route }: Props<'Pairing'>) { const { data } = useStore(); const [step, setStep] = useState(0); const [plantId, setPlant] = useState(route.params?.plantId ?? data.plants[0]?.id ?? ''); const [wifi, setWifi] = useState(''); const [name, setName] = useState('ESP32 Soil Sensor'); return <Page back={() => step ? setStep(step - 1) : navigation.goBack()} footer={<Button title={step === 2 ? 'Continue to calibration' : step === 0 ? 'Use demo device' : 'Continue'} icon="arrow-forward" disabled={!plantId || !name.trim()} onPress={() => step < 2 ? setStep(step + 1) : navigation.navigate('Calibration', { plantId, name })}/>}><Title center>Connect a sensor</Title><Txt style={s.sub}>Connect an ESP32 to a plant in your garden.</Txt><Chips values={['Find device', 'Network', 'Link plant']} value={['Find device', 'Network', 'Link plant'][step]} onChange={v => setStep(['Find device', 'Network', 'Link plant'].indexOf(v))}/><Enter key={step}><View style={{ gap: 18 }}>{step === 0 && <><View style={[s.split, { backgroundColor: C.pale, borderRadius: 24, padding: 18 }]}><PlantImage kind="peace-lily" size={180}/><Icon name="hardware-chip-outline" size={48}/></View><Field label="Device name" value={name} onChangeText={setName}/><Notice title="Demo discovery" text="Bluetooth discovery is not connected. The backend also supports direct HTTP readings from your ESP32."/></>}{step === 1 && <><Field label="Network label (optional)" value={wifi} onChangeText={setWifi} placeholder="Home Wi-Fi"/><Notice title="Provision Wi-Fi on the ESP32" text="This preview does not send Wi-Fi credentials. Use your existing firmware’s setup, then configure its API URL and device token." icon="wifi-outline"/></>}{step === 2 && <><Txt style={s.bold}>Choose a plant</Txt>{data.plants.map(p => <Pressable accessibilityRole="radio" accessibilityState={{ checked: p.id === plantId }} key={p.id} onPress={() => setPlant(p.id)}><Card style={{ borderColor: p.id === plantId ? C.green : C.border }}><View style={s.split}><PlantImage kind={p.kind} size={65}/><Txt style={{ flex: 1 }}>{p.name}</Txt><Icon name={p.id === plantId ? 'radio-button-on' : 'radio-button-off'} color={C.green}/></View></Card></Pressable>)}</>}</View></Enter></Page>; }
export function Calibration({navigation,route}:Props<'Calibration'>){
 const {data,update}=useStore();const existing=data.sensors.find(sensor=>sensor.demo&&sensor.plantId===route.params.plantId);
 const [dry,setDry]=useState(String(existing?.dry??3295));const [wet,setWet]=useState(String(existing?.wet??1422));const [raw,setRaw]=useState(existing?.moisture!=null?String(Math.round(existing.dry-existing.moisture/100*(existing.dry-existing.wet))):'2771');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 let value:number|null=null;try{if([dry,wet,raw].every(v=>/^\d+$/.test(v)))value=moisture(Number(raw),Number(dry),Number(wet));}catch{}
 const save=async()=>{if(busy)return;setError('');if(value===null){setError('Enter whole ADC values from 0 to 4095. Dry must be greater than wet.');return;}setBusy(true);try{await update(d=>{const demo=d.sensors.find(sensor=>sensor.demo&&sensor.plantId===route.params.plantId);const id=demo?.id??`demo-sensor-${Date.now()}`;return {...d,sensors:[...d.sensors.filter(sensor=>sensor.id!==id),{id,plantId:route.params.plantId,name:route.params.name,dry:Number(dry),wet:Number(wet),moisture:value,source:'SENSOR',observedAt:new Date().toISOString(),demo:true}]};});navigation.dispatch(state=>{const start=state.routes.findIndex(r=>r.name==='Pairing'||r.name==='Calibration');const base=state.routes.slice(0,start<0?1:start);const routes=base.at(-1)?.name==='Sensors'?base:[...base,{name:'Sensors'}];return CommonActions.reset({...state,routes,index:routes.length-1});});}catch(e){setError(e instanceof Error?e.message:'Could not save calibration.');}finally{setBusy(false);}};
 return <Page back={navigation.goBack} footer={<Button title={busy?'Saving…':'Save demo calibration'} icon="checkmark" disabled={busy} onPress={save}/>}><Title center>Calibrate sensor</Title><Txt style={s.sub}>Record dry and wet reference values for the soil sensor.</Txt><Card><Txt small>Simulated reading</Txt><Title>{value===null?'—':`${value}%`}</Title><MoistureProgress value={value}/><Txt small>{value===null?'Check the ADC values below.':'Derived from the ADC values below'}</Txt></Card><Field label="Dry reading (air) · ADC" value={dry} onChangeText={v=>{setDry(v);setError('');}} numeric/><Field label="Wet reading · ADC" value={wet} onChangeText={v=>{setWet(v);setError('');}} numeric/><Field label="Sample reading · ADC" value={raw} onChangeText={v=>{setRaw(v);setError('');}} numeric/><Notice title="Demonstration only" text="These samples stay separate from real hardware readings and never change your plant’s measured state."/>{!!error&&<Txt style={{color:C.orange}}>{error}</Txt>}</Page>;
}
