import React, { useEffect, useRef, useState } from 'react';
import { AccessibilityInfo, Animated, Easing, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View, ViewStyle, KeyboardAvoidingView, Platform } from 'react-native';
import Motion, { useSharedValue, useAnimatedStyle, withSpring } from 'react-native-reanimated';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PlantKind } from './model';
import { useStore } from './store';
export const C = { bg: '#F7F9EF', ink: '#343D27', muted: '#646C59', green: '#67B923', dark: '#414D2E', pale: '#EAF2DF', border: '#E6E9DF', white: '#FFFFFF', orange: '#A64124', pink: '#FFF0E9', blue: '#409AD1' };
export const images = { aloe: require('../assets/aloe-reference.png'), 'peace-lily': require('../assets/peace-lily-reference.png'), monstera: require('../assets/monstera-reference.png') };
export type IconName = React.ComponentProps<typeof Ionicons>['name'];
export function Icon({ name, size = 22, color = C.dark }: { name: IconName; size?: number; color?: string }) { return <Ionicons name={name} size={size} color={color} />; }
export function Txt({ children, style, small = false }: React.PropsWithChildren<{ style?: any; small?: boolean }>) { return <Text style={[small ? s.small : s.text, style]}>{children}</Text>; }
export function Title({ children, center = false }: React.PropsWithChildren<{ center?: boolean }>) { return <Text accessibilityRole="header" style={[s.title, center && { textAlign: 'center' }]}>{children}</Text>; }
export function Logo({ large = false }: { large?: boolean }) { return <Image source={require('../assets/logo-reference.png')} accessibilityLabel="Rootera" resizeMode="contain" style={{ width: large ? 245 : 127, height: large ? 64 : 34 }}/>; }

const MotionPressable = Motion.createAnimatedComponent(Pressable);
export function Button({ title, onPress, secondary = false, icon, disabled = false }: { title: string; onPress: () => void; secondary?: boolean; icon?: IconName; disabled?: boolean }) {
 const reduce=useReducedMotion(); const pressed=useSharedValue(1);
 const animated=useAnimatedStyle(()=>({transform:[{scale:pressed.value}]}));
 return <MotionPressable accessibilityRole="button" accessibilityLabel={title} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} onPressIn={()=>{pressed.value=withSpring(reduce?1:.97,{duration:130,dampingRatio:1});}} onPressOut={()=>{pressed.value=withSpring(1,{duration:180,dampingRatio:1});}} style={[s.button,secondary&&s.secondary,{opacity:disabled?.45:1},animated]}><Txt style={{color:secondary?C.ink:C.white,fontFamily:'NunitoSans_700Bold',textAlign:'center'}}>{title}</Txt>{icon&&<Icon name={icon} size={20} color={secondary?C.dark:C.white}/>}</MotionPressable>;
}
export function IconButton({ name, onPress, label }: { name: IconName; onPress: () => void; label: string }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({ pressed }) => ({ padding: 11, opacity: pressed ? .5 : 1 })}><Icon name={name}/></Pressable>; }
export function Card({ children, style }: React.PropsWithChildren<{ style?: ViewStyle }>) { return <View style={[s.card, style]}>{children}</View>; }
export function Badge({ text, warning = false }: { text: string; warning?: boolean }) { return <View style={[s.badge, warning && { backgroundColor: C.pink }]}><Txt small style={{ fontFamily: 'NunitoSans_700Bold', color: warning ? C.orange : '#467821' }}>{text}</Txt></View>; }
export function PlantImage({ kind = 'aloe', size = 180, uri }: { kind?: PlantKind; size?: number; uri?: string }) { return <Image source={uri ? { uri } : images[kind]} accessibilityLabel={kind.replace('-', ' ')} style={{ width: size, height: size, borderRadius: 0 }} resizeMode="contain"/>; }
export function Row({ icon, title, value, onPress }: { icon: IconName; title: string; value?: string; onPress?: () => void }) { const content = <><Icon name={icon}/><Txt style={{ flex: 1 }}>{title}</Txt>{!!value && <Txt small style={{ maxWidth: '47%', textAlign: 'right', color: C.ink }}>{value}</Txt>}{onPress && <Icon name="chevron-forward" size={17} color={C.muted}/>}</>; return onPress ? <Pressable onPress={onPress} accessibilityRole="button" style={({ pressed }) => [s.row, { opacity: pressed ? .6 : 1 }]}>{content}</Pressable> : <View style={s.row}>{content}</View>; }
export function Field({ label, value, onChangeText, placeholder, secure, numeric }: { label: string; value: string; onChangeText: (s: string) => void; placeholder?: string; secure?: boolean; numeric?: boolean }) { return <View style={{ gap: 7 }}><Txt small style={{ fontFamily: 'NunitoSans_700Bold', color: C.ink }}>{label}</Txt><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={C.muted} secureTextEntry={secure} keyboardType={numeric ? 'number-pad' : 'default'} style={s.input}/></View>; }
export function Chips<T extends string>({ values, value, onChange }: { values: readonly T[]; value: T; onChange: (v: T) => void }) { return <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{values.map(v => <Pressable accessibilityRole="button" accessibilityState={{ selected: v === value }} key={v} onPress={() => onChange(v)} style={[s.chip, v === value && { backgroundColor: C.dark, borderColor: C.dark }]}><Txt small style={{ color: v === value ? 'white' : C.ink }}>{v}</Txt></Pressable>)}</View>; }
export function Notice({ title, text, icon = 'information-circle-outline' }: { title: string; text: string; icon?: IconName }) { return <View style={s.notice}><Icon name={icon} color="#56872B"/><View style={{ flex: 1, gap: 3 }}><Txt style={{ fontFamily: 'NunitoSans_700Bold', fontSize: 14 }}>{title}</Txt><Txt small>{text}</Txt></View></View>; }
export function Page({ children, back, right, header, footer, center = false, scrollRef, onScroll, tabScreen = false, hideStorageError = false }: React.PropsWithChildren<{ back?: () => void; right?: React.ReactNode; footer?: React.ReactNode; header?: React.ReactNode; center?: boolean; scrollRef?: React.RefObject<ScrollView | null>; onScroll?: React.ComponentProps<typeof ScrollView>['onScroll']; tabScreen?: boolean; hideStorageError?: boolean }>) {
 const { storageError } = useStore();
 return <SafeAreaView edges={tabScreen ? ['top', 'left', 'right'] : ['top', 'bottom', 'left', 'right']} style={s.safe}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={{ flex: 1 }}>
 {(back || right || header) && <View style={[s.top, header ? { height: 62, paddingHorizontal: 22 } : undefined]}>{back ? <IconButton name="chevron-back" onPress={back} label="Go back"/> : header || <View/>}{right}</View>}
 <ScrollView ref={scrollRef} onScroll={onScroll} scrollEventThrottle={16} keyboardShouldPersistTaps="handled" contentInsetAdjustmentBehavior="automatic" contentContainerStyle={[s.content, center && { flexGrow: 1, justifyContent: 'center' }]} showsVerticalScrollIndicator={false}>{!!storageError && !hideStorageError && <Txt small style={{ color: C.orange }}>{storageError}</Txt>}{children}</ScrollView>
 {footer && <View style={s.footer}>{footer}</View>}</KeyboardAvoidingView></SafeAreaView>;

}
export function useReducedMotion() { const [reduce, set] = useState(true); useEffect(() => { AccessibilityInfo.isReduceMotionEnabled().then(set).catch(()=>set(true)); const sub = AccessibilityInfo.addEventListener('reduceMotionChanged', set); return () => sub.remove(); }, []); return reduce; }
export function Enter({ children, delay = 0, style }: React.PropsWithChildren<{ delay?: number; style?: ViewStyle }>) {
 const reduce = useReducedMotion(); const progress = useRef(new Animated.Value(1)).current;
 useEffect(() => { if (reduce) { progress.setValue(1); return; } progress.setValue(0); const a = Animated.timing(progress, { toValue: 1, delay, duration: 220, easing: Easing.out(Easing.cubic), useNativeDriver: true }); a.start(); return () => a.stop(); }, [reduce, delay]);
 return <Animated.View style={[style, { opacity: progress, transform: [{ translateY: progress.interpolate({ inputRange: [0, 1], outputRange: [8, 0] }) }, { scale: 1 }] }]}>{children}</Animated.View>;
}
export const s = StyleSheet.create({
 safe: { flex: 1, backgroundColor: C.bg }, top: { height: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12 }, content: { paddingHorizontal: 22, paddingTop: 12, paddingBottom: 22, gap: 16 }, footer: { padding: 22, paddingTop: 12, gap: 10, backgroundColor: C.bg }, text: { fontFamily: 'NunitoSans_400Regular', color: C.ink, fontSize: 16, lineHeight: 22 }, small: { fontFamily: 'NunitoSans_400Regular', color: C.muted, fontSize: 13, lineHeight: 19 }, title: { fontFamily: 'NunitoSans_800ExtraBold', fontSize: 26, lineHeight: 31, color: C.ink, letterSpacing: -.7 }, button: { backgroundColor: C.dark, borderRadius: 12, borderCurve: 'continuous', minHeight: 52, paddingVertical: 13, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10 }, secondary: { backgroundColor: C.white, borderWidth: 1, borderColor: C.dark }, card: { backgroundColor: C.white, borderWidth: 1, borderColor: C.border, borderRadius: 16, borderCurve: 'continuous', padding: 16, gap: 12 }, badge: { alignSelf: 'flex-start', paddingHorizontal: 11, paddingVertical: 5, borderRadius: 12, backgroundColor: '#E3F1D5' }, row: { flexDirection: 'row', gap: 12, alignItems: 'center', paddingVertical: 16, minHeight: 52, borderBottomWidth: 1, borderBottomColor: C.border }, notice: { padding: 16, gap: 12, flexDirection: 'row', alignItems: 'center', backgroundColor: C.pale, borderRadius: 14, borderCurve: 'continuous' }, input: { backgroundColor: C.white, borderWidth: 1, borderColor: C.border, borderRadius: 14, minHeight: 52, padding: 14, color: C.ink, fontFamily: 'NunitoSans_400Regular', fontSize: 15 }, chip: { borderWidth: 1, borderColor: C.border, borderRadius: 20, minHeight:44, justifyContent:'center', paddingHorizontal: 14, paddingVertical: 10, backgroundColor: C.white }, split: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, bold: { fontFamily: 'NunitoSans_700Bold' }, center: { alignItems: 'center' }, sub: { color: C.muted, textAlign: 'center', lineHeight: 22 }, link: { color: '#4D7E28', fontFamily: 'NunitoSans_700Bold' }
});
